-- Inbox / sent log for Email manager. Same RLS pattern as public.users.

create table if not exists public.emails (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  direction text not null check (direction in ('sent', 'received')),
  from_addr text not null,
  to_addr text not null,
  subject text not null,
  html text,
  text text,
  status text not null,
  provider_result jsonb,
  external_id text
);

create unique index if not exists emails_external_id_uidx
  on public.emails (external_id)
  where external_id is not null;

create index if not exists emails_created_at_idx
  on public.emails (created_at desc);

alter table public.emails enable row level security;

drop policy if exists emails_all on public.emails;
create policy emails_all on public.emails
  for all using (true) with check (true);

grant select, insert, update, delete on public.emails to anon, authenticated, service_role;
grant usage, select on all sequences in schema public to anon, authenticated, service_role;
