-- Outbound transfers. Matches the Dashboard table:
--   id identity, user_id text, sendings_id_fkey on id → users(id) is optional.
-- The server writes user_id as text and, while sendings_id_fkey exists,
-- sets id to a free users.id so the insert is accepted.

create table if not exists public.sendings (
  id bigint generated by default as identity not null,
  created_at timestamptz not null default now(),
  status text null,
  failure_message text null,
  recipient_address text null,
  amount text null,
  user_id text null,
  constraint sendings_pkey primary key (id),
  constraint sendings_status_check check (
    status is null or status in ('pending', 'success', 'failure')
  )
);

-- Optional: drop the id→users FK so identity can emit 1, 2, 3… freely.
-- Safe to skip. The server still inserts if this constraint stays.
alter table public.sendings drop constraint if exists sendings_id_fkey;

create index if not exists sendings_user_id_idx on public.sendings (user_id);

alter table public.sendings add column if not exists asset_symbol text;

create index if not exists sendings_created_at_idx on public.sendings (created_at desc);

-- RLS policies live in sendings-rls.sql. Do not recreate USING (true).
alter table public.sendings enable row level security;

drop policy if exists sendings_all on public.sendings;
