export {
  ADDRESS_LENGTH,
  MAX_UINT256,
  SELECTOR_LENGTH,
  WORD_LENGTH,
  decodeAddress,
  decodeBool,
  decodeUint,
  encodeAddressWord,
  encodeCall,
  encodeCallWithAddress,
  encodeCallWithAddressAndUint,
  encodeCallWithTwoAddresses,
  encodeCallWithUint,
  encodeUintWord,
  eventTopic,
  functionSelector,
  readAddressWord,
  strip,
} from './encoding'
